name: Build, Publish, and Auto-Deploy Backend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tony203/youcreate

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -f ./pom.xml clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:latest 
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: Logout from Docker Hub
        run: docker logout

      #- name: Deploy to Render
      #  env:
       #   deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
       # run: |
      #    curl -X GET ${{ env.deploy_url }}